#!/bin/bash

set -e

RUN_AS="server"
CORES=2
THREAD="false"
RAM=1024
kernel_path=""
rootfs_path=""

while [ ! -z "$1" ]
do
	case "$1" in
		-c|--client)
			RUN_AS="client"
			;;
		-j|--cores)
			CORES="$2"
			shift
			;;
		-t|--thread)
			THREAD="true"
			;;
		-m|--ram)
			RAM=$(( 1024*$2 ))
			shift
			;;
		-k|--kernel)
			kernel_path=$2
			shift
			;;
		-r|--root)
			rootfs_path=$2
			shift
			;;
		-int|--interactive)
			INTERACTIVE="yes"
			;;
		-i|--initramfs)
			INITRAMFS=$2
			shift
			;;
		*)
			if [[ "$kernel_path" == "" ]]; then
				kernel_path=$1
			else
				rootfs_path=$1
			fi
			;;
	esac
	shift
done

if [[ "$RUN_AS" == "server" ]]; then
	rm -f /tmp/firecracker.socket
	firecracker --api-sock /tmp/firecracker.socket
fi

if [[ "$RUN_AS" == "client" ]]; then
	K_STR="{ \"kernel_image_path\": \"${kernel_path}\""
	if [[ "$INTERACTIVE" == "yes" ]]; then
		K_STR+=",\"boot_args\": \"console=ttyS0 reboot=k panic=1\""
	fi
	if [[ -n "$INITRAMFS" ]]; then
		K_STR+=",\"initrd_path\": \"${INITRAMFS}\""
	fi
	K_STR+=" }"

	curl --unix-socket /tmp/firecracker.socket -i \
		-X PUT 'http://localhost/boot-source'     \
		-H 'Accept: application/json'             \
		-H 'Content-Type: application/json'       \
		-d "$K_STR"

	curl --unix-socket /tmp/firecracker.socket -i \
		-X PUT 'http://localhost/drives/rootfs'   \
		-H 'Accept: application/json'             \
		-H 'Content-Type: application/json'       \
		-d "{
			\"drive_id\": \"rootfs\",
			\"path_on_host\": \"${rootfs_path}\",
			\"is_root_device\": true,
			\"is_read_only\": false
		}"

	curl --unix-socket /tmp/firecracker.socket -i  \
		-X PUT 'http://localhost/machine-config'   \
		-H 'Accept: application/json'              \
		-H 'Content-Type: application/json'        \
		-d "{
			\"vcpu_count\": $CORES,
			\"mem_size_mib\": $RAM,
			\"ht_enabled\": $THREAD
		}"

	curl --unix-socket /tmp/firecracker.socket -i     \
	 	-X PUT 'http://localhost/network-interfaces/eth0' \
		-H 'Accept: application/json'                     \
		-H 'Content-Type: application/json'               \
		-d '{
			"iface_id": "eth0",
			"guest_mac": "AA:BB:00:00:00:01",
			"host_dev_name": "tap0"
		}'

	curl --unix-socket /tmp/firecracker.socket -i \
		-X PUT 'http://localhost/actions'         \
		-H  'Accept: application/json'            \
		-H  'Content-Type: application/json'      \
		-d '{
			"action_type": "InstanceStart"
		}'
fi
