#!/bin/bash

FC=/home/mm/bin/fc

pkill firecracker
sleep 1
rm /tmp/firecracker*.socket 2> /dev/null
sudo umount fireclust/o* 2> /dev/null
rm -rf fireclust

if [[ $1 != "clean" ]]; then
	for (( i=0; i<$2; i++)); do
	 	$FC server &
	 	sleep 1
	done

	mkdir -p fireclust/base
	cp $1 fireclust/base/OS.ext4
	cp $1 fireclust/master.ext4

	for (( i=0; i<$2; i++)); do
		mkdir -p fireclust/{w$i,u$i,o$i}
		sudo mount -t overlay -o \
			lowerdir=fireclust/base,upperdir=fireclust/u$i,workdir=fireclust/w$i \
			none fireclust/o$i
	done

	for (( i=0; i<$2; i++)); do
		$FC -c -r fireclust/o$i/OS.ext4 -k ~/code/linux/vmlinux -m 4 -j 2 -n --socket $i &
		sleep 1
	done
	sleep 60
	echo "doing nmap"
	nmap 192.168.0.* -p 22 | grep open -B 4 | grep 192 | awk '{ print $5; }'
fi

