#!/bin/bash

FC=/home/mm/bin/fc

BASE=""
KERNEL=~/code/linux/vmlinux
AMT=3

usage() {
	echo -e "fc-clust [options]"
	echo -e "\t-r|--root: root partition to be used (eg root.ext4)"
	echo -e "\t-k|--kernel: Kernel to be used (default $KERNEL)"
	echo -e "\t-n|--count: number of virtual machines to be run (default $AMT)"
	echo -e "\t-c|--clean: clean up any running cluster"
}

while [[ ! -z $1 ]]; do
	case $1 in
		-r|--root)
			BASE=$2
			shift
			;;
		-k|--kernel)
			KERNEL=$2
			shift
			;;
		-n|--count)
			AMT=$2
			shift
			;;
		-c|--clean)
			CLEAN="yes"
			;;
		-h|--help)
			usage
			exit
			;;
		*)
			echo "Unknown Command"
			exit
	esac
	shift
done

pkill firecracker
sleep 1
rm /tmp/firecracker*.socket 2> /dev/null
sudo umount fireclust/o* 2> /dev/null
rm -rf fireclust

if [[ $CLEAN != "yes" && $BASE != "" ]]; then
	for (( i=0; i<$AMT; i++)); do
	 	$FC &
	 	sleep 1
	done

	mkdir -p fireclust/base
	cp $BASE fireclust/base/OS.ext4

	for (( i=0; i<$AMT; i++)); do
		mkdir -p fireclust/{w$i,u$i,o$i}
		sudo mount -t overlay -o \
			lowerdir=fireclust/base,upperdir=fireclust/u$i,workdir=fireclust/w$i \
			none fireclust/o$i
	done

	for (( i=0; i<$AMT; i++)); do
		$FC -c -r fireclust/o$i/OS.ext4 -k $KERNEL -m 4 -j 2 -n --socket $i &
		sleep 1
	done
	sleep 60
	echo "doing nmap"
	nmap 192.168.0.* -p 22 | grep open -B 4 | grep 192 | awk '{ print $5; }'
fi

