#!/bin/bash

HOST_NET=$(ip link | awk '{ print $2; }' | grep en | sed 's/://g')
NETWORK="192.168.0."
BR_IP=$NETWORK+"3"
GW_IP=$NETWORK+"1"

clean_tap() {
	TAPS=$(ip a | grep tap | awk '{ print $2; }' | sed 's/://g')
	for t in $TAPS; do
		sudo ip link set $t nomaster
		sudo ip link del $t
	done
}

if [[ $1 == "up" ]]; then
	shift
	sudo ip link add name br0 type bridge
	sudo ip link set dev br0 up
	sudo ip link set dev $HOST_NET up
	sudo ip addr flush dev $HOST_NET
	sudo ip link set dev $HOST_NET master br0
	sudo ip addr add $BR_IP/24 dev br0
	sudo ip route add default via $GW_IP dev br0

	sudo iptables -A FORWARD -p all -i br0 -j ACCEPT

elif [[ $1 == "down" ]]; then
	shift
    clean_tap
	sudo ip link set dev $HOST_NET nomaster
	sudo ip link del dev br0
	sudo ip link set dev $HOST_NET down
	sudo ip link set dev $HOST_NET up
elif [[ $1 == "ct" ]]; then
	clean_tap
fi
